---
title: "DATA 607 Week 7 Assignment: HTML, XML, JSON Parsing"
author: "Ilya Kats"
date: "March 18, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<STYLE>
table {
    border: 1px solid black;
}
th {
    background-color: rgb(112, 196, 105);
    color: white;
    font-weight: bold;
    padding: 20px 30px;
}
tr:nth-child(even) {
    background-color: rgb(220,220,220);
}
tr:nth-child(odd) {
    background-color: rgb(255, 255, 255);
}
</STYLE>

## Required Libraries

```{r requirements, results='hide', message=FALSE}
library(dplyr)
library(stringr)
library(XML)
library(RCurl)
library(tidyjson)
```

## Data Import: HTML

```{r}
htmlFile <- getURL("https://raw.githubusercontent.com/ilyakats/CUNY-DATA607/master/books.html")
booksHTML <- readHTMLTable(htmlFile, header = TRUE)
```

## Data Import: XML

```{r}
xmlFile <- getURL("https://raw.githubusercontent.com/ilyakats/CUNY-DATA607/master/books.xml")
booksXML <- xmlParse(xmlFile, validate = TRUE)
```

## Data Import: JSON

```{r}
jsonFile <- getURL("https://raw.githubusercontent.com/ilyakats/CUNY-DATA607/master/books.json", .encoding = "Windows-1252")

books <- jsonFile %>% 
  enter_object("scifi_books") %>% 
  gather_array("book.id") %>% 
  spread_values(title = jstring("title"), 
                author = jstring("author"),
                year = jnumber("year"), 
                isbn = jstring("isbn"))

awards <- jsonFile %>% 
  enter_object("scifi_books") %>% 
  gather_array("book.id") %>% 
  enter_object("award") %>% 
  gather_array() %>% 
  spread_values(award.name = jstring("name"),
                award.year = jnumber("year"))

films <- jsonFile %>% 
  enter_object("scifi_books") %>% 
  gather_array("book.id") %>% 
  enter_object("film") %>% 
  gather_array() %>% 
  spread_values(film.title = jstring("name"),
                film.director = jstring("director"),
                film.year = jnumber("year"))


books %>% 
  left_join(awards, by = "book.id") %>% 
  left_join(films, by = "book.id") %>% 
  select(book.id, title, author, year, isbn, award.name, award.year, 
         film.title, film.director, film.year)
```

## Conclusion

TBD